### ISSUE TITLE
EL6 status

### ISSUE THREAD

**Issue by b-harper** [iuscommunity-pkg/stunnel5u#1]
With the 5.42 release, a new BuildRequires is needed, autoconf-archive.  That package is [not available for EL6][0].  We are trying to determine the best way to proceed.  EL6 is in [Production 3 Phase][1] (only critical security patches), these types of issues will come up.  An option we are considering is dropping EL6 support.

@Xon or other users, I am curious your thoughts on the possibility of dropping EL6 support.

[0]: https://bugzilla.redhat.com/show_bug.cgi?id=1313438
[1]: https://access.redhat.com/support/policy/updates/errata/#Production_3_Phase

**Comment by Xon** [comment]
I've moved off EL6 for all my use-cases for stunnel5u, so dropping support for EL6 isn't an issue.

**Comment by b-harper** [comment]
@Xon, thanks for the feedback.  

The EL7 5.42 packages will be hitting the testing repositories during tonight's automation.  I'll leave this issue open till we are ready to move those packages into the stable repositories to allow other to give feedback.  If we do not get any feedback, we will drop EL6 support.

**Comment by b-harper** [comment]
Seeing that we have not gotten any additional feedback, we will proceed with only packaging stunnel5u for EL7.
